### ISSUE TITLE
Support for dependency's field injection.

### ISSUE THREAD

**Issue by zooeywm** [ZihanType/rudi#1]
When inject a specific field from a struct, for example, I think it would be better to code like this:

```rust
// Register async function and specify name
#[Singleton(name = "number")]
async fn Number() -> u32 {
    42
}

#[derive(Debug, Clone)]
#[Singleton(name = "config")] // Register async constructor and specify name
struct Config{
    #[di(name = "number")] // Specify the name of the dependency
    max_user: u32,
}

#[derive(Debug)]
struct Bar(i32);

impl Bar {
    fn into_debug(self) -> Rc<dyn Debug> {
        Rc::new(self)
    }
}

#[Transient(binds = [Self::into_debug])] // Bind the implementation of the `Debug` trait and the trait object of the `Debug` trait
impl Bar {
    async fn new(#[di(name = "config.max_user")] max_user: u32) -> Bar { // Register async constructor
        Bar(max_user)
    }
}
```

**Comment by ZihanType** [comment]
In the above example, there are 3 things worth noting.

1. `#[di(name = "number")] max_user: u32,`, which is written to find the instance with name `"number"` and type `u32` from the `Context`, not to register this instance to the `Context`.

2. `Config` is registered to `Context` as a whole, its internal fields are not registered to `Context`.

3. `#[di(name = "config.max_user")] max_user: u32`, which is written in such a way that it is trying to find an instance with the name `"config.max_user"` and type `u32` from the Context, is not found.

**Comment by zooeywm** [comment]
Thanks for your reply, I can understand the things you list, my understanding was also same as you when I first raised the issue. 
My issue isn't a problem, it is an possibly “enhance”

> `#[di(name = "config.max_user")] max_user: u32`, which is written in such a way that it is trying to find an instance with the name `"config.max_user"` and type `u32` from the Context, is not found.

In my imagine with this thing: `#[di(name = "config.max_user")] max_user: u32`:
If the `Context` can recognize the `.` symbol as a signal to look for `max_user` field of the **whole registered `Config`** which dependency-name is specified to `config`, then extract the field here, would be better than this:

```rust
#[derive(Debug)]
struct Bar(Config);

#[Transient(binds = [Self::into_debug])] // Bind the implementation of the `Debug` trait and the trait object of the `Debug` trait
impl Bar {
    async fn new(#[di(name = "config")] config: Config) -> Bar { // Register async constructor
        Bar(config.max_user)
    }
}
```

**Comment by ZihanType** [comment]
All instances stored in the `Context` are of type `Box<dyn Any>`, and the corresponding instance cannot be found by a name `"config.max_user"` or `"config"` alone. You have to use the name plus the type as a unique key to find the corresponding `Box<dyn Any>` instance, and then convert it to an instance of a specific type. So `#[di(name = "config")] config: Config` works, `#[di(name = "config.max_user")] max_user: u32` does not.
