### ISSUE TITLE
eager_create configuration does not take effect

### ISSUE THREAD

**Issue by litcc** [ZihanType/rudi#4]
Example code:
```rust

use rudi::Context;
use rudi_macro::Singleton;

#[Singleton(eager_create)]
fn Run() {
    println!("Run()");
}


#[test]
fn singleton_owned() {
    Context::auto_register();

    Context::options().eager_create(false).auto_register();

    Context::options().eager_create(false).allow_only_single_eager_create(false).auto_register();


}
```

Anticipation:
Only the first one that defaults to true executes the Run, the rest of the ones specified as false do not execute anything with eager_create

![image](https://github.com/ZihanType/rudi/assets/13202561/f6a6a445-a21e-4c23-8185-4fbf95003479)

The code in the red box in the figure and is seen to validate the eager_create configuration.

I also have a question for you. 
Why is the function call in the red box in the above picture called twice in flash, is there any special mechanism? I'm sorry I don't have a thorough understanding of the project's source code, so I'd like to ask

**Comment by ZihanType** [comment]
1. First of all, the `eager_create` field in `Context` and `ContextOptions` is `false` by default, so the `eager_create` field in the `Context` created by `Context::auto_register();` in the above code is still `false`.

2. whether an instance is eagerly created depends on the `eager_create` field of the `Provider` that defines it, the `eager_create` field of the `Module` to which this `Provider` belongs, and the `eager_create` field of the `Context` to which this `Module` belongs. As long as one of these is `true`, then the instance is eagerly created.

3. `Context::evaluate_providers(...)` method calls the `Context::load_provider(...)` method. In the `load_provider` method, the `Providers` evaluated for eager creation are put into the queue `Context::eager_create_functions`. Then in the `Context::create_eager_instances(...)` method will iterate through this queue and create these instances.
